### ISSUE TITLE
Support Latest Release of Urllib3

### ISSUE THREAD

**Issue by collindutter** [marqo-ai/py-marqo#263]
Hello!

`py-marqo` requires an [older version](https://github.com/marqo-ai/py-marqo/blob/fbf4d7b54f9e20917a6f37a17a54755b20657965/requirements.txt#L2) of [urllib3](https://github.com/urllib3/urllib3) which does not support python 3.13. Since the usage of urllib seems [fairly limited](https://github.com/marqo-ai/py-marqo/blob/fbf4d7b54f9e20917a6f37a17a54755b20657965/src/marqo/utils.py#L3), is this something that you would consider updating to the [latest release](https://github.com/urllib3/urllib3/releases)?

Thanks!

**Comment by papa99do** [comment]
Hello @collindutter , sorry for the late reply. We pinned the urllib3 version to `<2.0.0` due to a SSL certificate issue when talk ing to Marqo Cloud in Jan 2024. I've done a quick test yesterday and it seems the issue is gone using the latest 2.x version. I'll verify with the Marqo team again and unpin the version in the next release so you can specify the latest in Griptape.

**Comment by collindutter** [comment]
Fantastic, thanks @papa99do!

**Comment by collindutter** [comment]
Resolved with `3.9.2` on [PyPi](https://pypi.org/project/marqo/) 🥳
